server:
  port: 8082

spring:
  application:
    name: USER-SERVICE
  config:
    import: configserver:http://localhost:8085
   
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/microservices
    password: Krishna12#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-91501614.okta.com/oauth2/default
      client: 
        registration:
          my-internal-client: 
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal 
            client-id: 0oaa26bo2lwldAqx95d7
            client-secret: RNtIBz4R58WDbJwo2YwlP4BDyLCOFV9_qNT2-ErC
            
        provider:
          okta:
            issuer-uri: https://dev-91501614.okta.com/oauth2/default
    
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always



resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s
        

okta:
  oauth2:
    issuer: https://dev-91501614.okta.com/oauth2/default
    audience: api://default
    
        

          
        
     